MODNOTES-233 Do not include # of notes assigned to note types in response
folio-org/mod-notes pull request #217
Opened 2022-07-08 10:03 UTC by maryna-steshenko

## Purpose
Improve mod-notes performance by not returning a total number of notes assigned to a note type. 

## Approach
- Instead of a total number a value indicating whether a note type is assigned to any note is returned
- Corresponding changes to unit tests are made

2022-07-08 12:49 UTC, psmagin requested changes

2022-07-08 12:49 UTC, psmagin commented on src/main/java/org/folio/notes/domain/repository/NoteTypesRepository.java
>    List<NoteTypeCount> findNoteUsage(@Param("noteTypeIds") List<UUID> noteTypeIds);
```suggestion
  List<NoteTypeCount> findNoteUsage();
```
Let's remove these ids and query for all note types (we have programmatic limitations for the number of note types). I think it simplifies queries and will improve its performance.

2022-07-08 12:49 UTC, psmagin commented on src/main/java/org/folio/notes/domain/repository/NoteTypesRepository.java
> +  @Query("SELECT t.id as typeId, EXISTS (SELECT n.type.id FROM NoteEntity AS n WHERE n.type.id = t.id) as isAssigned FROM NoteTypeEntity as t WHERE t.id IN (:noteTypeIds)")
```suggestion
  @Query("SELECT t.id as typeId, EXISTS (SELECT n.type.id FROM NoteEntity AS n WHERE n.type.id = t.id LIMIT 1) as isAssigned FROM NoteTypeEntity as t WHERE t.id IN (:noteTypeIds)")
```
It's enough to have at least one record  in the subquery

2022-07-08 12:49 UTC, psmagin commented on src/main/resources/swagger.api/schemas/noteType.yaml
> +          description: Is this note type assigned to any note
It's a breaking change of the API. The interface version should be increased.

2022-07-08 12:51 UTC, psmagin commented
This PR couldn't be merged until UI changes will be applied and all dependent modules change the dependent interface version.

2022-07-12 10:59 UTC, psmagin approved these changes

2022-07-12 11:33 UTC, marcjohnson-kint commented on descriptors/ModuleDescriptor-template.json
> +      "version": "3.0",
This version change should be reflected in the YAML file describing the interface

(it is currently version 1.0, which suggests to me that the previous breaking change also did not change this)

2022-07-12 11:33 UTC, marcjohnson-kint commented on descriptors/ModuleDescriptor-template.json
> +      "version": "3.0",
As the APIs provided by this module are now incompatible with the APIs provided by previous versions, this is a major implementation breaking change.

That should be reflected in a major version change for the module.

2022-07-13 11:24 UTC, zburke commented
@maryna-steshenko, what is the timeline for merging this change? I see [MODNOTES-233](https://issues.folio.org/browse/MODNOTES-233) is targeted for Nolana. This not only affects ui-notes but also stripes-smart-components, which potentially makes this a breaking change for all of stripes and thus for every single UI application. 

Depending on what SSC does (or ignores) with the mod-notes API responses, we maybe able to change support from `"2"` to `"2 || 3"` and avoid the breaking change in stripes, but we need some time to investigate. @BogdanDenis, I see your name attached to some SSC commits related to `lib/Notes`. Is this something you could potentially investigate, or do you know who could?

2022-07-13 11:35 UTC, BogdanDenis commented
> @maryna-steshenko, what is the timeline for merging this change? I see [MODNOTES-233](https://issues.folio.org/browse/MODNOTES-233) is targeted for Nolana. This not only affects ui-notes but also stripes-smart-components, which potentially makes this a breaking change for all of stripes and thus for every single UI application.
> 
> Depending on what SSC does (or ignores) with the mod-notes API responses, we maybe able to change support from `"2"` to `"2 || 3"` and avoid the breaking change in stripes, but we need some time to investigate. @BogdanDenis, I see your name attached to some SSC commits related to `lib/Notes`. Is this something you could potentially investigate, or do you know who could?

@zburke this change will only affect note types, and we have a ticket ([UINOTES-132](https://issues.folio.org/browse/UINOTES-132)) to account for this, we'll change API version there
But for SSC interface version 2 or 3 shouldn't matter because Notes don't use `/note-types` endpoint that was changed or the `usage.noteTotal` property that was removed - is that correct, @maryna-steshenko?
I'll create additional tickets to clean up things like test stubs and prop types in SSC and other modules.

2022-07-19 12:45 UTC, merged